// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Counter$SimpleCounter = require("./Counter.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Counter$SimpleCounter.make(/* array */[])), "app");

/*  Not a pure module */
